devtools::use_data_raw()
devtools::document()
devtools::use_data(gb_load, overwrite = TRUE)
devtools::use_data(clust_train)
devtools::use_data(clust_test)
devtools::use_package('magrittr')
devtools::use_package('lubridate')
devtools::use_package('dplyr')
devtools::use_package('stats')
usethis::use_build_ignore('cran-comments.md')
usethis::use_build_ignore('NEWS.md')
